Update testRigor.yml

diff --git a/.github/workflows/testRigor.yml b/.github/workflows/testRigor.yml
--- a/.github/workflows/testRigor.yml
+++ b/.github/workflows/testRigor.yml
@@ -24,48 +24,50 @@ jobs:
       - name: Run a multi-line script
         run: |
     
-                      curl -X POST \
-                        -H 'Content-type: application/json' \
-                        -H 'auth-token: 33eecc6c-a54a-479a-a0b1-b014cacd0b93' \
-                        --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
-                        https://api.testrigor.com/api/v1/apps/oSs7743pfTyq6nLGv/retest
-                      
-                      sleep 10
-                      
-                      while true
-                      do
-                        echo " "
-                        echo "==================================="
-                        echo " Checking TestRigor retest"
-                        echo "==================================="
-                        response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/oSs7743pfTyq6nLGv/status' -H 'auth-token: 33eecc6c-a54a-479a-a0b1-b014cacd0b93' -H 'Accept: application/json')
-                        code=$(echo "$response" | grep HTTP |  awk '{print $2}')
-                        body=$(echo "$response" | sed -n '/{/,/}/p')
-                        echo "Status code: " $code
-                        echo "Response: " $body
-                        case $code in
-                          4*|5*)
-                            # 400 or 500 errors
-                            echo "Error calling API"
-                            exit 1
-                            ;;
-                          200)
-                            # 200: successfully finished
-                            echo "Test finished successfully"
-                            exit 0
-                            ;;
-                          227|228)
-                            # 227: New - 228: In progress
-                            echo "Test is not finished yet"
-                            ;;
-                          230)
-                            # 230: Failed
-                            echo "Test finished but failed"
-                            exit 1
-                            ;;
-                          *)
-                            echo "Unknown status"
-                            exit 1
-                          esac
-                        sleep 10
-                      done
+                     #!/bin/bash
+
+curl -X POST \
+  -H 'Content-type: application/json' \
+  -H 'auth-token: 02f58bff-7e13-47d7-8e4b-dc9f6e833985' \
+  --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+  https://api.testrigor.com/api/v1/apps/ukecWYsrpDQXK7otn/retest
+
+sleep 10
+
+while true
+do
+  echo " "
+  echo "==================================="
+  echo " Checking TestRigor retest"
+  echo "==================================="
+  response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/ukecWYsrpDQXK7otn/status' -H 'auth-token: 02f58bff-7e13-47d7-8e4b-dc9f6e833985' -H 'Accept: application/json')
+  code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+  body=$(echo "$response" | sed -n '/{/,/}/p')
+  echo "Status code: " $code
+  echo "Response: " $body
+  case $code in
+    4*|5*)
+      # 400 or 500 errors
+      echo "Error calling API"
+      exit 1
+      ;;
+    200)
+      # 200: successfully finished
+      echo "Test finished successfully"
+      exit 0
+      ;;
+    227|228)
+      # 227: New - 228: In progress
+      echo "Test is not finished yet"
+      ;;
+    230)
+      # 230: Failed
+      echo "Test finished but failed"
+      exit 1
+      ;;
+    *)
+      echo "Unknown status"
+      exit 1
+    esac
+  sleep 10
+done
